### ISSUE TITLE
fastbot运行时异常，log报错如下

### ISSUE THREAD

**Issue by zhangzhao4444** [zhangzhao4444/Fastbot_Android#1]
[Fastbot][2024-07-05 17:01:39.401] Internal error
java.lang.IncompatibleClassChangeError: The method 'java.lang.Class java.lang.Object.getClass()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'com.android.commands.monkey.framework.APIAdapter' appears in /sdcard/monkeyq.jar)
at com.android.commands.monkey.framework.APIAdapter.setActivityController(APIAdapter.java:196)
at com.android.commands.monkey.Monkey.getSystemInterfaces(Monkey.java:1283)
at com.android.commands.monkey.Monkey.run(Monkey.java:718)
at com.android.commands.monkey.Monkey.main(Monkey.java:460)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:389)

**Comment by zhangzhao4444** [comment]
@marscode
